### ISSUE TITLE
the welcome page goes to the wrong `chats` page

### ISSUE THREAD

**Issue by hydazz** [bitswired/ai-chat-app#1]
when clicking the `Start By Visiting The Chat Page To Create A New Chat` button it redirects you to `/chat`, which does not exists (should be `/chats`), you probably are already aware of this but..

**Comment by hydazz** [comment]
`favicon.ico` also appears to be corrupted

**Comment by jimzer** [comment]
Hi man thank you for reporting this 👍🏽.
Indeed that was a mistake.

I've seen your PR, thank you very much for the contribution.
However we worked at the same time and I pushed a new major version of the web app with lots of improvements, and the introduction of templates and smart templates.
Can you check if it solves the issues you've fixed in the PR? (I also added a logo and a customized favicon).
Otherwise we can adapt it to the new code.

You can now set your API key in a /settings page.
(I updated the video in the README to introduces the changes).
You can maybe try the new version and let me know what you think?
Feel free to open PR if you see any problems.

(Sorry for the messy updates, I will work with PR only now that people start contributing 🙏🏽)

**Comment by hydazz** [comment]
Great work 👍 everything seems fine now (for a brand new app)

_(The old brain logo looked cooler than the new robot btw)_

**Comment by jimzer** [comment]
Thanks @hydazz!
I'm glad it's working for you :)

Ah too bad ^^ I tried to generate a more unique one (with Midjourney ahah) the old "brain" one was from a generic icon repository.

Don't know if you have design skills but if you want to propose a new logo, I will be happy to work on it with you!
